import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { JSDOM } from 'jsdom';
import { courseChangeTool, mountWorkspaceNavigation } from '../src/main/resources/static/workspace-nav.js';

test('course changes keep the course-wide recording view when appropriate',()=>{
  assert.equal(courseChangeTool('recording-panel'), 'recording-panel');
  assert.equal(courseChangeTool('recording-panel',{noteId:'note-1'}), 'note');
  assert.equal(courseChangeTool('recording-panel',{dashboardVisible:true}), 'note');
  assert.equal(courseChangeTool('recording-panel',{dashboardVisible:true,restoreRecording:true}), 'recording-panel');
  assert.equal(courseChangeTool('note',{restoreRecording:true}), 'recording-panel');
  assert.equal(courseChangeTool('learning-panel'), 'note');
});

test('recording opens a focused workspace and navigation keeps controls mounted',()=>{
  const dom=new JSDOM(readFileSync(new URL('../src/main/resources/static/index.html',import.meta.url),'utf8'));
  const doc=dom.window.document;
  assert.equal(doc.getElementById('dashboard-semester'),null);
  assert.equal(doc.querySelector('.today-dashboard-card .eyebrow').textContent,"TODAY'S CLASSES");
  assert.equal(doc.querySelector('.today-dashboard-card h3').textContent,'오늘 수업');
  assert.equal(doc.querySelectorAll('#tips-panel .tips-grid article').length,6);
  assert.equal(doc.getElementById('tips-title').textContent,'나중에 다시 보기 좋은 노트 쓰기');
  assert.match(doc.querySelector('#tips-panel .tips-heading .muted').textContent,/수업 내용을 모두 받아 적을 필요는 없어요/);
  assert.match(doc.querySelector('#tips-panel .tips-template code').textContent,/## 질문과 헷갈린 점/);
  assert.match(doc.querySelector('#tips-panel .tips-template code').textContent,/## 다음 수업까지 할 일/);
  const selectedTools=[];
  doc.addEventListener('studyspace:tool-selected',event=>selectedTools.push(event.detail.id));
  mountWorkspaceNavigation(doc);
  const body=doc.getElementById('note-body');body.value='저장 전 필기';
  const buttons=doc.querySelectorAll('.workspace-tabs button');
  assert.equal(buttons.length,4);
  assert.equal(buttons[0].textContent,'노트');
  assert.equal(buttons[1].textContent,'강의자료');
  assert.equal(buttons[2].textContent,'녹음');
  assert.equal(buttons[3].textContent,'AI 학습');
  assert.equal(doc.querySelector('.workspace-context').textContent,'목록에서 열람할 노트를 선택해주세요');
  assert.equal(doc.querySelector('.workspace-context').hidden,false);
  assert.equal(doc.title,'StudySpace | 로그인');
  doc.getElementById('note-title').value='8-31 1차시';
  doc.getElementById('auth-card').classList.add('hidden');
  doc.getElementById('dashboard').classList.add('hidden');
  doc.dispatchEvent(new dom.window.Event('studyspace:note-opened'));
  assert.equal(doc.querySelector('.workspace-context').hidden,true);
  assert.equal(doc.title,'StudySpace | 8-31 1차시 · 강의노트');
  assert.equal(doc.getElementById('attachment-panel').hidden,true);
  buttons[1].click();
  assert.equal(doc.getElementById('attachment-panel').hidden,false);
  assert.equal(doc.title,'StudySpace | 8-31 1차시 · 강의자료');
  doc.dispatchEvent(new dom.window.Event('studyspace:note-opened'));
  assert.equal(doc.getElementById('attachment-panel').hidden,false);
  assert.equal(buttons[1].getAttribute('aria-pressed'),'true');
  buttons[2].click();
  assert.equal(doc.getElementById('attachment-panel').hidden,true);
  assert.equal(doc.getElementById('recording-panel').hidden,false);
  assert.equal(doc.querySelector('.writing-panel').hidden,true);
  assert.equal(doc.getElementById('study').classList.contains('tool-mode'),true);
  assert.ok(doc.getElementById('rail-recording-status'));
  assert.ok(doc.getElementById('rail-recording-clock'));
  doc.dispatchEvent(new dom.window.Event('studyspace:note-opened'));
  assert.equal(doc.getElementById('recording-panel').hidden,false);
  assert.equal(buttons[2].getAttribute('aria-pressed'),'true');
  buttons[3].click();
  assert.equal(selectedTools.at(-1),'learning-panel');
  assert.equal(doc.getElementById('learning-panel').hidden,false);
  assert.equal(doc.getElementById('recording-panel').hidden,true);
  const learningTabs=doc.querySelectorAll('#learning-tabs [data-learning-view]');
  assert.equal(learningTabs.length,4);
  assert.deepEqual([...learningTabs].map(button=>button.textContent),['요약','인포그래픽','퀴즈','플래시카드']);
  assert.equal(doc.getElementById('learning-panel').querySelector('#learning-tabs').nextElementSibling.id,'learning-summary-view');
  assert.equal(doc.querySelector('.writing-panel').hidden,true);
  doc.getElementById('notes').click();
  assert.equal(body.value,'저장 전 필기');
  assert.equal(doc.getElementById('recording-panel').hidden,true);
  assert.equal(doc.querySelector('.workspace-tabs button:nth-child(3)').getAttribute('aria-pressed'),'false');
  assert.equal(doc.querySelector('.course-menu').parentElement,doc.querySelector('#study aside'));
  assert.equal(doc.getElementById('dashboard-semester').closest('.course-rail') !== null,true);
  assert.equal(doc.querySelector('.rail-brand img.brand-logo')?.getAttribute('src'),'/assets/studyspace-logo.png');
  const brandButton=doc.querySelector('.rail-brand-button');
  assert.equal(brandButton?.getAttribute('aria-label'),'StudySpace 홈');
  let dashboardClicks=0;
  doc.getElementById('dashboard-button').addEventListener('click',()=>dashboardClicks++);
  brandButton.click();
  assert.equal(dashboardClicks,1);
  assert.equal(doc.querySelector('.rail-section-label .course-management') !== null,true);
  const courseManagement=doc.querySelector('.rail-section-label .course-management');
  const courseManagementSummary=courseManagement.querySelector(':scope > summary');
  assert.equal(courseManagementSummary.textContent,'관리');
  courseManagementSummary.click();
  assert.equal(courseManagement.open,true);
  assert.equal(courseManagement.querySelector('.course-management-popover-head strong').textContent,'과목 관리');
  courseManagement.querySelector('.course-management-close').click();
  assert.equal(courseManagement.open,false);
  assert.equal(doc.querySelector('.course-menu #tips-tab')?.previousElementSibling?.textContent,'수업노트');
  assert.deepEqual([...doc.querySelectorAll('.course-menu button')].map(button=>button.textContent.trim()),['학습 현황','수업노트','작성 팁']);
  assert.equal(doc.getElementById('speed-quiz-menu-button'),null);
  assert.equal([...doc.querySelectorAll('.course-menu button')].some(button=>button.textContent.includes('퀴즈 생성')),false);
  assert.equal(doc.querySelector('.rail-footer'),null);
  const railToggle=doc.querySelector('.rail-toggle');
  assert.equal(railToggle.textContent,'목록 접기');
  railToggle.click();
  assert.equal(doc.getElementById('study').classList.contains('note-rail-collapsed'),true);
  assert.equal(railToggle.textContent,'›');
  assert.equal(railToggle.getAttribute('aria-expanded'),'false');
  doc.querySelector('.workspace-tabs button:nth-child(2)').click();
  assert.equal(doc.getElementById('study').classList.contains('note-rail-collapsed'),true);
  railToggle.click();
  assert.equal(doc.getElementById('study').classList.contains('note-rail-collapsed'),false);
  assert.equal(railToggle.textContent,'목록 접기');
  doc.getElementById('tips-tab').click();
  assert.equal(doc.getElementById('tips-panel').classList.contains('hidden'),false);
  assert.equal(doc.getElementById('dashboard').classList.contains('hidden'),true);
  assert.equal(doc.getElementById('dashboard-button').getAttribute('aria-pressed'),'false');
  assert.equal(doc.getElementById('tips-tab').getAttribute('aria-pressed'),'true');
  railToggle.click();
  doc.dispatchEvent(new dom.window.CustomEvent('studyspace:select-tool',{detail:{id:'recording-panel'}}));
  assert.equal(doc.getElementById('study').classList.contains('note-rail-collapsed'),true);
  assert.equal(doc.getElementById('study').classList.contains('tool-mode'),true);
  assert.equal(doc.getElementById('recording-panel').hidden,false);
  doc.dispatchEvent(new dom.window.CustomEvent('studyspace:select-tool',{detail:{id:'generation-panel'}}));
  assert.equal(doc.getElementById('learning-panel').hidden,false);
  doc.dispatchEvent(new dom.window.CustomEvent('studyspace:select-tool',{detail:{id:'practice'}}));
  assert.equal(doc.getElementById('tips-panel').classList.contains('hidden'),true);
  assert.equal(doc.getElementById('note-editor-card').classList.contains('hidden'),false);
  assert.equal(doc.getElementById('learning-panel').hidden,false);
  doc.dispatchEvent(new dom.window.Event('studyspace:course-changing'));
  assert.equal(doc.getElementById('study').classList.contains('note-rail-collapsed'),false);
  assert.equal(railToggle.textContent,'목록 접기');
  assert.equal(doc.querySelector('.workspace-context').hidden,false);
  doc.getElementById('note-form').classList.add('hidden');
  doc.dispatchEvent(new dom.window.Event('studyspace:course-changing'));
  doc.dispatchEvent(new dom.window.CustomEvent('studyspace:select-tool',{detail:{id:'recording-panel'}}));
  assert.equal(doc.getElementById('note-form').classList.contains('hidden'),false);
  assert.equal(doc.getElementById('recording-panel').hidden,false);
  assert.equal(doc.querySelector('.workspace-tabs button:nth-child(3)').getAttribute('aria-pressed'),'true');
  assert.equal(doc.querySelector('.workspace-context').hidden,true);
  doc.dispatchEvent(new dom.window.CustomEvent('studyspace:select-tool',{detail:{id:'note'}}));
  doc.dispatchEvent(new dom.window.Event('studyspace:note-opened'));
  assert.equal(doc.querySelector('.workspace-context').hidden,true);
  doc.dispatchEvent(new dom.window.Event('studyspace:note-closed'));
  assert.equal(doc.querySelector('.workspace-context').hidden,false);
  dom.window.close();
});
